
GET http://localhost:3000/countrywithusergrouped
Accept: application/json

###
GET http://localhost:3000/countrywithuser
Accept: application/json

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "id_country": 2,
  "gender": "masculine",
  "birthday": "2022-04-23T18:25:43.511Z",
  "name": "andres",
  "lastname": "alejandro",
  "nickname": "josea",
  "email": "jose@gmai.com"
}

###
POST http://localhost:3000/item
Content-Type: application/json

{
  "name": "ultimoItem",
  "price": 2.3,
  "offer": 5.4
}

###
GET http://localhost:3000/items
Accept: application/json

###


